pipeline{
    //Directives
    agent any
    tools{
        maven 'maven'

    }
}

stages {
    // Specify various stage within stages

    // Stage 1. Build

    stage ('Build'){
        steps {
            sh 'mvn clean install package'
        }
    }


    // Stage 2. Test

    stage ('Test'){
        steps {
            echo '\n Testing... \n'
        }
    }


    // Stage 3. Deploying

    stage ('Deploy'){
        steps {
            echo '\n Deploying... \n'
        }
    }

}